project: 
  type: website
  output-dir: docs

website:
  title: "My Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        href: ./aboutme.html
      - text: "Projects"
        menu:
          - text: "R Coding Exercise"
            href: ./coding_exercise.html
          - text: "Data Analysis Exercise"
            href: ./dataanalysis_exercise/code/dataanalysis_exercise.html
          - text: "Visualization Exercise"
            href: ./visualization_exercise.html
          - text: "Tidy Tuesday Exercise"
            href: ./tidytuesday_exercise.html
          - text: "Tidy Tuesday Exercise 2"
            href: ./tidytuesday_exercise2.html
      - text: "Flu Analysis"
        menu:
          - text: "Wrangling"
            href: ./fluanalysis/code/wrangling.html
          - text: "Exploration"
            href: ./fluanalysis/code/exploration.html
          - text: "Fitting"
            href: ./fluanalysis/code/fitting.html
          - text: "Fitting"
            href: ./fluanalysis/code/modeleval.html
    right:
      - icon: github 
        href: https://github.com/sethlattner/sethlattner-MADA-portfolio.git        

format:
  html:
    theme: cosmo
    highlight: zenburn
    css: styles.css
    toc: FALSE


